namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.ComponentModel.TypeConverter.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Diagnostics.Process.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Diagnostics.TextWriterTraceListener.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Diagnostics.TraceSource.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Reflection.Metadata.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Reflection.TypeExtensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Runtime.InteropServices.RuntimeInformation.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Runtime.Serialization.Json.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Runtime.Serialization.Primitives.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Threading.Thread.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net461/System.Xml.XPath.XmlDocument.fsx" 
#r "/home/justin/.nuget/packages/microsoft.testplatform.objectmodel/15.9.0/lib/net451/Microsoft.TestPlatform.PlatformAbstractions.dll" 
#r "/home/justin/.nuget/packages/microsoft.testplatform.objectmodel/15.9.0/lib/net451/Microsoft.TestPlatform.CoreUtilities.dll" 
#r "/home/justin/.nuget/packages/microsoft.testplatform.objectmodel/15.9.0/lib/net451/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll" 