namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.Diagnostics.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.HostFiltering.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.Hosting.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.Routing.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.Server.IISIntegration.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.Server.Kestrel.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.AspNetCore.Server.Kestrel.Https.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Configuration.CommandLine.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Configuration.EnvironmentVariables.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Configuration.FileExtensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Configuration.Json.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Configuration.UserSecrets.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Logging.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Logging.Configuration.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Logging.Console.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarintvos/Microsoft.Extensions.Logging.Debug.csx" 