namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.AspNetCore.WebUtilities.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.Extensions.Configuration.Binder.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.Extensions.Options.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/Microsoft.Net.Http.Headers.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/System.Memory.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/System.Numerics.Vectors.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/System.Runtime.CompilerServices.Unsafe.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/System.Security.Cryptography.Cng.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard2.0/System.Threading.Tasks.Extensions.fsx" 
#r "/home/justin/.nuget/packages/microsoft.aspnetcore.server.kestrel.core/2.1.3/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll" 