namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.AspNetCore.Http.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.Configuration.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.Configuration.EnvironmentVariables.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.Configuration.FileExtensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.DependencyInjection.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.FileProviders.Physical.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.Hosting.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.Logging.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/Microsoft.Extensions.Options.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/System.Diagnostics.DiagnosticSource.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/xamarinios/System.Reflection.Metadata.fsx" 
#r "/home/justin/.nuget/packages/microsoft.aspnetcore.hosting/2.1.1/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.dll" 