namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Authentication.Core.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Authorization.Policy.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Http.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Mvc.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.ResponseCaching.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.AspNetCore.Routing.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.Extensions.DependencyInjection.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.Extensions.DependencyModel.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.Extensions.FileProviders.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netcoreapp2.2/System.Diagnostics.DiagnosticSource.fsx" 
#r "/home/justin/.nuget/packages/microsoft.aspnetcore.mvc.core/2.1.3/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Core.dll" 