namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.AspNetCore.Authentication.Core.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.AspNetCore.Http.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.AspNetCore.HttpOverrides.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/Microsoft.Extensions.Options.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/System.Buffers.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/System.IO.Pipelines.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/System.Memory.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/System.Numerics.Vectors.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/System.Runtime.CompilerServices.Unsafe.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.0/System.Security.Principal.Windows.fsx" 
#r "/home/justin/.nuget/packages/microsoft.aspnetcore.server.iisintegration/2.1.2/lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll" 