namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.ComponentModel.TypeConverter.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Diagnostics.Process.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Diagnostics.TextWriterTraceListener.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Reflection.Metadata.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Reflection.TypeExtensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Runtime.InteropServices.RuntimeInformation.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Runtime.Loader.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Runtime.Serialization.Json.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Threading.Thread.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/uap10.0.16300/System.Xml.XPath.XmlDocument.fsx" 
#r "/home/justin/.nuget/packages/microsoft.testplatform.objectmodel/15.9.0/lib/netstandard1.4/Microsoft.TestPlatform.PlatformAbstractions.dll" 
#r "/home/justin/.nuget/packages/microsoft.testplatform.objectmodel/15.9.0/lib/netstandard1.4/Microsoft.TestPlatform.CoreUtilities.dll" 
#r "/home/justin/.nuget/packages/microsoft.testplatform.objectmodel/15.9.0/lib/netstandard1.4/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll" 