namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Collections.Concurrent.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Linq.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Reflection.Emit.ILGeneration.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Reflection.Emit.Lightweight.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Reflection.TypeExtensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Runtime.Serialization.Primitives.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Text.RegularExpressions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Threading.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Xml.ReaderWriter.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Xml.XDocument.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Xml.XmlDocument.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/netstandard1.6/System.Xml.XmlSerializer.csx" 
#r "/home/justin/.nuget/packages/system.private.datacontractserialization/4.3.0/lib/netstandard1.3/System.Private.DataContractSerialization.dll" 