namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.AspNetCore.Hosting.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.AspNetCore.Http.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.AspNetCore.Http.Extensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.Configuration.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.Configuration.EnvironmentVariables.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.Configuration.FileExtensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.DependencyInjection.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.FileProviders.Physical.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.Hosting.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.Logging.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/Microsoft.Extensions.Options.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Diagnostics.DiagnosticSource.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Reflection.Metadata.csx" 
#r "/home/justin/.nuget/packages/microsoft.aspnetcore.hosting/2.1.1/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.dll" 