namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Buffers.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Collections.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Diagnostics.Debug.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.IO.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Resources.ResourceManager.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Runtime.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Runtime.Extensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Runtime.Handles.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Runtime.InteropServices.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Text.Encoding.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Threading.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Threading.Tasks.csx" 
#r "/home/justin/.nuget/packages/system.io.compression/4.3.0/lib/net46/System.IO.Compression.dll" 