namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Collections.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Diagnostics.Debug.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Linq.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Linq.Expressions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.ObjectModel.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Reflection.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Reflection.Emit.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Reflection.Emit.ILGeneration.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Reflection.Primitives.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Reflection.TypeExtensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Resources.ResourceManager.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Runtime.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Runtime.Extensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net472/System.Threading.fsx" 