namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/Microsoft.IdentityModel.Logging.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/Newtonsoft.Json.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Collections.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Diagnostics.Tools.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Reflection.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.Extensions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.InteropServices.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.InteropServices.RuntimeInformation.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.Serialization.Xml.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Security.Claims.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Security.Cryptography.Algorithms.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Security.Cryptography.X509Certificates.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Text.RegularExpressions.fsx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Threading.fsx" 
#r "/home/justin/.nuget/packages/microsoft.identitymodel.tokens/5.3.0/lib/net461/Microsoft.IdentityModel.Tokens.dll" 