namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/Microsoft.IdentityModel.Logging.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/Newtonsoft.Json.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Collections.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Diagnostics.Tools.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Reflection.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.Extensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.InteropServices.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.InteropServices.RuntimeInformation.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Runtime.Serialization.Xml.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Security.Claims.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Security.Cryptography.Algorithms.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Security.Cryptography.X509Certificates.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Text.RegularExpressions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/net471/System.Threading.csx" 
#r "/home/justin/.nuget/packages/microsoft.identitymodel.tokens/5.3.0/lib/net461/Microsoft.IdentityModel.Tokens.dll" 