namespace PaketLoadScripts

#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Authentication.Core.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Authorization.Policy.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Hosting.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Http.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Http.Extensions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Mvc.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.ResponseCaching.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.AspNetCore.Routing.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.Extensions.DependencyInjection.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.Extensions.DependencyModel.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.Extensions.FileProviders.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/Microsoft.Extensions.Logging.Abstractions.csx" 
#load "/home/justin/code/fsharp/GiraffeWebApp/GiraffeWebApp/.paket/load/monoandroid8.1/System.Diagnostics.DiagnosticSource.csx" 
#r "/home/justin/.nuget/packages/microsoft.aspnetcore.mvc.core/2.1.3/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Core.dll" 